###
POST http://localhost:3001/api/readinglists
Content-Type: application/json

{
  "blogId": 8,
  "userId": 1
}

###
PUT http://localhost:3001/api/readinglists/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1vb21pbkBnbWFpbC5jb20iLCJpZCI6MSwiaWF0IjoxNjU0NDMxOTEyfQ.eVdjKArucxMfNZrIL0hwC-_-gKKJTQXe4jcdisuK9VU
Content-Type: application/json

{
  "read": true
}
